export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_OFFICES = 'GET_OFFICES';

export const CREATE_TICKET = 'CREATE_TICKET';
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';
export const CREATE_TICKET_FAILURE = 'CREATE_TICKET_FAILURE';

export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE';
export const FETCH_TICKETS = 'FETCH_TICKETS';

export const FETCH_TICKET_DETAILS_SUCCESS = 'FETCH_TICKET_DETAILS_SUCCESS';
export const FETCH_TICKET_DETAILS_FAILURE = 'FETCH_TICKET_DETAILS_FAILURE';
export const FETCH_TICKET_DETAILS = 'FETCH_TICKET_DETAILS';

export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE';
export const ADD_MESSAGE = 'ADD_MESSAGE';

export const CLOSE_TICKET = 'CLOSE_TICKET';
export const CLOSE_TICKET_SUCCESS = 'CLOSE_TICKET_SUCCESS';
export const CLOSE_TICKET_FAILURE = 'CLOSE_TICKET_FAILURE';

export const ASSIGN_UPDATE_TICKET = 'ASSIGN_UPDATE_TICKET';
export const ASSIGN_UPDATE_TICKET_SUCCESS = 'ASSIGN_UPDATE_TICKET_SUCCESS';
export const ASSIGN_UPDATE_TICKET_FAILURE = 'ASSIGN_UPDATE_TICKET_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const SHOW_FORM_NEW_TICKET = 'SHOW_FORM_NEW_TICKET';

export const SHOW_LOADING_SCREEN = 'SHOW_LOADING_SCREEN';
export const DISMISS_LOADING_SCREEN = 'DISMISS_LOADING_SCREEN';





